server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: MiYuan-backend
  datasource:
    url: jdbc:mysql://localhost:3306/miyuan
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
